base_global_planner: "jps/JumpPointSearchROS"

JumpPointSearchPlanner:
  # If the goal is in an obstacle, the planer will plan to the nearest point in the radius of default_tolerance, default 0.0
  # The area is always searched, so could be slow for big values
  default_tolerance: 0.0
